site_name: 女性健康知识百科
site_description: 专业的女性健康知识分享平台
site_url: https://nellurkia.github.io/women-health-wiki/
repo_url: https://github.com/Nellurkia/women-health-wiki
repo_name: Nellurkia/women-health-wiki

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest

nav:
  - 首页: index.md
  - 生理健康:
    - 月经周期: physiology/menstrual-cycle.md
    - 子宫内膜异位症（测试页面）: physiology/neiyizheng.md
    - 月经用品: physiology/menstrual-pad.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex
  - pymdownx.tabbed
  - pymdownx.emoji
  - admonition
  - footnotes
